services:
  mocker-database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mocker_database
      - POSTGRES_USER=mocker_user
      - POSTGRES_PASSWORD=mocker_password
    ports:
      - 5432:5432